#define UART_DEVICE "/dev/console"  /* or "/dev/console_b" if you prefer */
#define LEON3 1

#define CONFIGURE_INIT
#define CONFIGURE_APPLICATION_NEEDS_CONSOLE_DRIVER
#define CONFIGURE_APPLICATION_NEEDS_CLOCK_DRIVER

#define CONFIGURE_MAXIMUM_TASKS             4

#define CONFIGURE_RTEMS_INIT_TASKS_TABLE

#define CONFIGURE_EXTRA_TASK_STACKS         (30 * RTEMS_MINIMUM_STACK_SIZE)

#define CONFIGURE_MAXIMUM_FILE_DESCRIPTORS	32

#define CONFIGURE_MAXIMUM_MESSAGE_QUEUES 4

